# Generated by Django 4.1 on 2022-12-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourisminfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='vehicle_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
