# Generated by Django 4.1 on 2022-11-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C_S', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='Timezone',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='country',
            name='capital',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
