# Generated by Django 4.1 on 2022-11-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C_S', '0002_alter_country_timezone_alter_country_capital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='population',
        ),
        migrations.AddField(
            model_name='state',
            name='districts',
            field=models.IntegerField(null=True),
        ),
    ]
